import { Activity, BookOpen, Bot, Cpu, FileText, FlaskConical, Home, Search, Settings, Shield } from "lucide-react"
import type { OnboardingStep } from "../types"

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    title: "首页",
    subtitle: "这里是平台总览入口。",
    Icon: Home,
    route: "/home",
    target: "nav-home",
    points: ["查看知识库、文档、助手和模型配置数量", "观察每日问答请求趋势", "从统计卡片快速进入常用模块"],
    action: "导览会先跳到首页，让你确认系统当前的数据概况。",
  },
  {
    title: "知识库",
    subtitle: "这里沉淀可被 AI 检索和引用的资料。",
    Icon: BookOpen,
    route: "/kb",
    target: "nav-kb",
    points: ["创建和启停知识库", "上传文档并预览解析结果", "管理文档条目，让问答更贴近业务内容"],
    action: "点击下一步会进入知识库页面，后续可以从这里开始导入资料。",
  },
  {
    title: "文档条目",
    subtitle: "这里集中查看已经进入知识库的文档。",
    Icon: FileText,
    route: "/items",
    target: "nav-kb-items",
    points: ["按知识库、状态和关键词筛选文档", "查看解析状态与启用情况", "进入详情页定位原文和分段内容"],
    action: "资料上传后，可在这里检查文档是否已可用于召回问答。",
  },
  {
    title: "问答助手",
    subtitle: "这里把知识库、提示词和模型组合成可用助手。",
    Icon: Bot,
    route: "/assistants",
    target: "nav-assistants",
    points: ["创建面向不同场景的助手", "绑定知识库并配置模型", "进入对话页面测试回答效果"],
    action: "配置完成后，进入聊天页用真实问题验证知识命中情况。",
  },
  {
    title: "评测数据集",
    subtitle: "这里把线上问题沉淀成可复跑的策略验证集。",
    Icon: FlaskConical,
    route: "/evals",
    target: "nav-evals",
    points: ["维护评测问题和参考答案", "标注相关 Chunk", "运行 Workflow baseline 与 Agent candidate"],
    action: "遇到回答失败时，可以从聊天页创建 EvalQuery 草稿，再回到这里完成标注。",
  },
  {
    title: "Agent 策略",
    subtitle: "这里管理候选策略、草稿和线上 active policy。",
    Icon: Shield,
    route: "/evals/policies",
    target: "nav-agent-policies",
    points: ["从 active 或 candidate run 创建 draft", "查看发布门槛和风险提示", "人工确认后发布唯一 active policy"],
    action: "策略不是自动上线；先用 EvalRun 证据验证，再由管理员确认发布。",
  },
  {
    title: "运行日志",
    subtitle: "这里下钻每次 Agent 的结构化执行 Trace。",
    Icon: Activity,
    route: "/agent-runs",
    target: "nav-agent-runs",
    points: ["查看工具调用、检索 Pass 和耗时", "定位 fallback 或预算耗尽", "从 Trace 打开引用原文"],
    action: "评测对比出现 improved 或 regressed 时，从这里解释 Agent 到底做了什么。",
  },
  {
    title: "召回调试台",
    subtitle: "这里用单条查询检查检索候选和原文证据。",
    Icon: Search,
    route: "/retrieval-debug",
    target: "nav-retrieval-debug",
    points: ["比较不同检索模式", "检查 Chunk 排名和分数", "打开文档详情定位原文"],
    action: "当某个样本退化时，先用调试台验证是检索问题还是 Agent 决策问题。",
  },
  {
    title: "模型供应商",
    subtitle: "这里配置助手调用的大模型能力。",
    Icon: Cpu,
    route: "/model-providers",
    target: "nav-model-providers",
    points: ["维护 OpenAI 兼容的模型供应商", "设置 API 地址和密钥", "统一管理助手可选择的模型服务"],
    action: "发布助手前，需要先准备至少一个可用的模型供应商。",
  },
  {
    title: "设置",
    subtitle: "这里处理账号操作，也能重新打开导览。",
    Icon: Settings,
    route: "/home",
    target: "nav-settings",
    points: ["修改本地账号密码", "退出当前登录", "点击“新手引导”重新查看这套说明"],
    action: "以后忘记模块用途时，从左下角设置菜单可以随时重看。",
  },
]
